server:
  port: 9090
spring:
  application:
    name: blog-service
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.address}
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_blog?characterEncoding=utf8&useSSL=false
    username: root
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  file:
    name: blog.log
---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
nacos:
  address: 117.72.211.70:8848
mysql:
  password: 212409

---
#生产环境
spring:
  config:
    activate:
      on-profile: prod
nacos:
  address: 127.0.0.1:8848
mysql:
  password: zRT3LJNYGz@