server:
  port: 8080
spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.address}
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_user?characterEncoding=utf8&useSSL=false
    username: root
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 60s #连接空闲超过N(s秒、ms毫秒)后关闭，0为禁用，这里配置值和tcp-keepalive值一致
      lettuce:
        pool:
          max-active: 8  #允许最大连接数
          max-idle: 8 #最大空闲连接数, 默认8
          min-idle: 0  #最小空闲连接数
          max-wait: 5s  #请求获取连接等待时间
  rabbitmq:
    addresses: amqp://bite:bite@117.72.211.70:5672/blog
    listener:
      simple:
        acknowledge-mode: manual   #手动确认
  mail:
    host: smtp.qq.com
    port: 587
    username: 2072855200@qq.com   # 登录账户
    password: loiizkzgdqzxcdda  # 登录密码/授权码
    properties:
      personal: "比特博客社区"
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false  # 使用 STARTTLS 而不是 SSL
          timeout: 25000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  file:
    name: user.log
---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
nacos:
  address: 117.72.211.70:8848
mysql:
  password: 212409

---
#生产环境
spring:
  config:
    activate:
      on-profile: prod
nacos:
  address: 127.0.0.1:8848
mysql:
  password: zRT3LJNYGz@