server:
  port: 10030
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 117.72.211.70:8848
    gateway:
      routes: #⽹关路由配置
        - id: user-service #路由ID, ⾃定义, 唯⼀即可
          uri: lb://user-service #⽬标服务地址
          predicates: #路由条件
            - Path=/user/**
        - id: blog-service
          uri: lb://blog-service
          predicates:
            - Path=/blog/**
      # 网关全局跨域配置
      globalcors:
        # 解决options请求被拦截的问题
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"     #设置允许跨域的来源
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
logging:
  file:
    name: gateway.log
---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
nacos:
  address: 117.72.211.70:8848

---
#生产环境
spring:
  config:
    activate:
      on-profile: prod
nacos:
  address: 127.0.0.1:8848