server:
  port: 10030
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 117.72.211.70:8848
    gateway:
#      metrics:
#        enabled: true # 打开全局过滤器
      routes: # 路由断言工厂
        - id: order-service   #路由规则id, 随便起, 不重复即可
          uri: lb://order-service/ #目标服务地址
          predicates:   #路由条件
            - Path=/order/**,/feign/**
            - After=2025-07-27T12:20:51.826479600+08:00[Asia/Shanghai]
          filters:
            - AddRequestParameter=userName, bite
            - name: Custom #过滤器名称
              args:
                name: test_custom # 参数名称
        - id: product-service
          uri: lb://product-service/
          predicates:
            - Path=/product/**
#      default-filters: # 路由过滤工厂
#        - name: Retry
#          args:
#            retries: 3
#            statuses: BAD_GATEWAY
# Global Filter
# http://127.0.0.1:10030/actuator 显示所有监控的信息连接
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always
#    shutdown:
#      enabled: true