server:
  port: 8080
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 117.72.211.70:8848
        # 停掉 nacos 删除 nacos 目录下的 /data/protocol/raft 信息，里面会保存应用实例的元数据信息
#        ephemeral: false # 将order-service 设置为非临时变量
#        namespace: 7b082872-2dbe-4d51-98a3-f2a26b987591
    # 由于Spring Cloud LoadBalance 组件自身有负载均衡配置方式，所以不支持 Nacos 的权重属性配置，所以需要开启 Nacos 的负载均衡策略，让权重配置生效
    loadbalancer:
      nacos:
        enabled: true
  profiles:
    active: @profile.name@
# 设置 Mybatis 的 xml 保存路径
mybatis:
  configuration: # 配置打印 MyBatis 执行的 SQL
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  #自动驼峰转换

# Feign 客户端配置
feign:
  client:
    config:
      default:
        connectTimeout: 10000  # 连接超时时间 10秒
        readTimeout: 30000     # 读取超时时间 30秒
        loggerLevel: FULL      # 开启详细日志
      product-service:
        connectTimeout: 8000   # 针对 product-service 的连接超时 8秒
        readTimeout: 20000     # 针对 product-service 的读取超时 20秒
        loggerLevel: FULL
  hystrix:
    enabled: true            # 启用熔断器
  compression:
    request:
      enabled: true          # 启用请求压缩
    response:
      enabled: true          # 启用响应压缩

# Hystrix 熔断器配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000  # 熔断器超时时间 30秒
    ProductApi#p1(Integer):
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000  # 针对 p1 方法的超时时间 20秒

# Ribbon 负载均衡配置
ribbon:
  ConnectTimeout: 8000       # Ribbon 连接超时
  ReadTimeout: 20000         # Ribbon 读取超时
  MaxAutoRetries: 1          # 最大重试次数
  MaxAutoRetriesNextServer: 2 # 最大重试下一个服务器次数